services:
  tg-bot:
    build:
      context: .
    container_name: tg-bot
    env_file:
      - ../.env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      main-db:
        condition: service_healthy
    volumes:
      - ../backend/services/main-service/storage:/app/storage
    networks:
      - main-network
    restart: unless-stopped
