services:
  tg-bot:
    build:
      context: .
    container_name: tg-bot
    env_file: ../.env
    environment:
      - MAIN_DB_HOST=main-db
    depends_on:
      main-db:
        condition: service_healthy
    volumes:
      - ../storage:/app/storage
    networks:
      - main-network
    restart: unless-stopped
