"""add phone, email, telegram, name to contacts

Revision ID: 2a71877d2db6
Revises: 525845b7379c
Create Date: 2026-08-19 18:46:52.378861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a71877d2db6'
down_revision: Union[str, None] = '525845b7379c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('telegram_username', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('email', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'contacts', ['telegram_username'])
    op.create_unique_constraint(None, 'contacts', ['email'])
    op.create_unique_constraint(None, 'contacts', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_column('contacts', 'name')
    op.drop_column('contacts', 'email')
    op.drop_column('contacts', 'telegram_username')
    op.drop_column('contacts', 'phone')
    # ### end Alembic commands ###
