"""add naming_help to order_requests

Revision ID: 39a6ea4907d3
Revises: ad58b25eb593
Create Date: 2026-08-15 16:52:12.493471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a6ea4907d3'
down_revision: Union[str, None] = 'ad58b25eb593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_requests', sa.Column('naming_help', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_requests', 'naming_help')
    # ### end Alembic commands ###
