"""add_categories_tables

Revision ID: 65dd6cb7b790
Revises: 39a6ea4907d3
Create Date: 2026-08-17 13:24:46.176706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65dd6cb7b790'
down_revision: Union[str, None] = '39a6ea4907d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('project_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('articles', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'articles', 'article_categories', ['category_id'], ['id'])
    op.add_column('projects', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'project_categories', ['category_id'], ['id'])
    op.drop_column('projects', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'category_id')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'category_id')
    op.drop_table('project_categories')
    op.drop_table('article_categories')
    # ### end Alembic commands ###
